"""
Baked-in schema reference compiled from DBeaver COLUMNS export.
Used by get_schema and query_data tools.
"""

TABLE_COLUMNS = {
    "accounts": ["id:bigint", "name:varchar", "company_id:bigint", "opening_balance:double", "bank_name:varchar", "bank_phone:varchar", "bank_address:longtext", "account_number:varchar", "ifsc_code:varchar", "upi_mobile:varchar", "upi_id:varchar", "default:enum", "currency_code:varchar", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "add_ons": ["id:bigint", "hsn_no:varchar", "title:varchar", "image:varchar", "category_id:bigint", "company_id:bigint", "description:text", "features:longtext", "tax_group_id:bigint", "price:double", "mrp:double", "purchase_price:double", "expiry_date:datetime", "days:bigint", "connection_type:enum", "status:enum", "bill_type:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "areas": ["id:bigint", "name:varchar", "area_code:varchar", "company_id:bigint", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "bq_ai_query_logs": ["id:bigint", "user_id:int", "company_id:bigint", "user_query:text", "effective_query:text", "intent:varchar", "service_used:varchar", "sql_used:text", "response_time_ms:int", "row_count:int", "success:tinyint", "error_message:text", "created_at:timestamp"],
    "bq_app_users": ["id:int", "email:varchar", "password_hash:varchar", "company_id:bigint", "role:enum", "status:enum", "created_at:timestamp", "approved_at:timestamp", "approved_by:int"],
    "categories": ["id:bigint", "company_id:bigint", "name:varchar", "type:enum", "color:varchar", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "companies": ["id:bigint", "bq_user_id:bigint", "name:varchar", "email:varchar", "country_code:varchar", "lco_code:varchar", "isp_code:varchar", "is_demandpay_enabled:tinyint", "phone:varchar", "tax_in:varchar", "logo:varchar", "address:text", "status:enum", "created_by:bigint", "deleted_by:bigint", "created_at:timestamp", "updated_at:timestamp", "deleted_at:timestamp"],
    "complaint_forums": ["id:bigint", "complaint_id:bigint", "comments:text", "customer_id:bigint", "company_id:bigint", "closed_by:bigint", "status:enum", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "complaints": ["id:bigint", "customer_id:bigint", "complaint_prefix:varchar", "complaint_no:bigint", "problem_type:varchar", "priority:enum", "stb_no:varchar", "problem_detail:text", "phone:varchar", "assigned_to:int", "image:varchar", "last_updated_by:bigint", "company_id:bigint", "start_date:timestamp", "area_id:bigint", "status:enum", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "currencies": ["id:bigint", "name:varchar", "code:varchar", "symbol:varchar", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "customer_add_on_histories": ["id:bigint", "customer_add_on_id:bigint", "customer_add_on_details:longtext", "customer_id:bigint", "customer_details:longtext", "subscription_id:bigint", "subscription_details:longtext", "add_on_id:bigint", "add_on_details:longtext", "company_id:bigint", "order_id:int", "start_date:datetime", "end_date:datetime", "recurring:enum", "payment_status:enum", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "customer_add_ons": ["id:bigint", "order_id:bigint", "customer_id:bigint", "subscription_id:bigint", "add_on_id:bigint", "stb_id:bigint", "stb_no:bigint", "company_id:bigint", "parent_user_id:bigint", "category_id:bigint", "description:text", "start_date:datetime", "end_date:datetime", "recurring:enum", "discount_type:enum", "discount:double", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "customer_dues_logs": ["id:bigint", "user_id:int", "company_id:int", "subscriber_id:varchar", "amount:double", "comments:text", "created_at:timestamp", "updated_at:timestamp"],
    "customer_subscription_histories": ["id:bigint", "customer_id:bigint", "company_id:bigint", "order_id:int", "package_id:bigint", "customer_subscription_id:bigint", "package_details:text", "customer_details:text", "subscription_details:text", "add_on_details:text", "created_by:bigint", "created_at:timestamp", "updated_at:timestamp"],
    "customer_subscriptions": ["id:bigint", "order_id:bigint", "customer_id:bigint", "package_id:bigint", "payment_id:bigint", "category_id:bigint", "payment_status:enum", "company_id:bigint", "parent_user_id:bigint", "stb_id:bigint", "stb_no:varchar", "package_details:longtext", "start_date:datetime", "end_date:datetime", "recurring:enum", "discount_type:enum", "discount:double", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "customers": ["id:bigint", "subscriber_id:varchar", "company_id:bigint", "parent_user_id:bigint", "lco_no:varchar", "first_name:varchar", "last_name:varchar", "email:varchar", "country_code:varchar", "mobile:varchar", "image:varchar", "password:varchar", "dues:double", "address:text", "latitude:varchar", "longitude:varchar", "dob:date", "tax_in:varchar", "currency_code:varchar", "reference:text", "area_id:bigint", "route_no:varchar", "join_date:timestamp", "billing_name:varchar", "billing_lastname:varchar", "billing_company_name:varchar", "billing_address:text", "status:enum", "customer_type:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "default_payment_methods": ["id:bigint", "company_id:bigint", "customer_app:bigint", "pos_machine:bigint", "agent_collection:bigint", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "demand_pay_access_logs": ["id:bigint", "company_id:bigint", "endpoint:varchar", "method:varchar", "ip_address:varchar", "request_payload:longtext", "request_headers:longtext", "created_at:timestamp", "updated_at:timestamp"],
    "demand_pay_tokens": ["id:bigint", "name:varchar", "token:varchar", "company_id:bigint", "is_active:tinyint", "expires_at:timestamp", "last_used_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "device_tokens": ["id:bigint", "user_id:int", "company_id:int", "device_token:varchar", "created_at:timestamp", "updated_at:timestamp"],
    "enquiries": ["id:bigint", "enquiry_id:varchar", "name:varchar", "country_code:varchar", "phone:varchar", "email:varchar", "address:text", "source:enum", "product_id:bigint", "assigned_to:bigint", "status:enum", "city:varchar", "area_id:int", "state:varchar", "country:varchar", "company:varchar", "company_id:bigint", "notes:text", "created_at:timestamp", "updated_at:timestamp"],
    "expenses": ["id:bigint", "company_id:bigint", "vendor_id:bigint", "header_id:bigint", "amount:double", "balance:double", "paid_amount:double", "paid_date:datetime", "type:enum", "payment_no:varchar", "payment_date:date", "bill_date:date", "due_date:date", "bill_no:varchar", "order_no:varchar", "payment_method:bigint", "account_id:bigint", "file:varchar", "description:text", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp", "payment_status:enum"],
    "failed_jobs": ["id:bigint", "uuid:varchar", "connection:text", "queue:text", "payload:longtext", "exception:longtext", "failed_at:timestamp"],
    "followups": ["id:bigint", "lead_id:bigint", "company_id:bigint", "followup_date:date", "next_followup_date:date", "remarks:text", "status:enum", "created_by:bigint", "created_at:timestamp", "updated_at:timestamp"],
    "headers": ["id:bigint", "title:varchar", "description:text", "status:enum", "company_id:bigint", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "incomes": ["id:bigint", "vendor_id:bigint", "header_id:bigint", "company_id:bigint", "amount:double", "balance:double", "paid_amount:double", "paid_date:datetime", "bill_date:date", "due_date:date", "bill_no:varchar", "order_no:varchar", "payment_method:bigint", "account_id:bigint", "file:varchar", "description:text", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp", "payment_status:enum"],
    "items": ["id:bigint", "hsn_no:varchar", "name:varchar", "sku:varchar", "image:varchar", "description:text", "sale_price:double", "purchase_price:double", "stock:int", "category_id:bigint", "tax_group_id:bigint", "company_id:bigint", "status:enum", "created_by:bigint", "last_updated_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "jobs": ["id:bigint", "queue:varchar", "payload:longtext", "attempts:tinyint", "reserved_at:int", "available_at:int", "created_at:int"],
    "leads": ["id:bigint", "lead_id:varchar", "enquiry_id:bigint", "name:varchar", "phone:varchar", "email:varchar", "stage:enum", "assigned_to:bigint", "expected_value:decimal", "next_followup_date:date", "remarks:text", "company_id:bigint", "created_at:timestamp", "updated_at:timestamp"],
    "master_plans": ["id:bigint", "user_id:bigint", "company_id:int", "bq_user_id:bigint", "package_name:varchar", "max_connections:bigint", "end_date:date", "sms_enable:enum", "sms_count:int", "status:enum", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "message_channel_settings": ["id:bigint", "company_id:int", "bq_user_id:int", "user_id:int", "sms_enabled:varchar", "whatsapp_enabled:varchar"],
    "message_notification_settings": ["id:bigint", "company_id:int", "user_id:int", "message_type:varchar", "sms_enabled:varchar", "whatsapp_enabled:varchar"],
    "migrations": ["id:int", "migration:varchar", "batch:int"],
    "model_has_permissions": ["permission_id:bigint", "model_type:varchar", "model_id:bigint"],
    "model_has_roles": ["role_id:bigint", "model_type:varchar", "model_id:bigint"],
    "notifications": ["id:bigint", "from_user_id:int", "to_user_id:int", "company_id:int", "complaint_id:int", "payment_id:int", "title:varchar", "message:text", "priority:enum", "read_status:tinyint", "created_at:timestamp", "updated_at:timestamp"],
    "order_histories": ["id:bigint", "customer_id:bigint", "company_id:bigint", "order_id:bigint", "status:enum", "order_details:longtext", "comments:text", "notify:tinyint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "order_item_taxes": ["id:bigint", "company_id:bigint", "order_id:bigint", "item_id:bigint", "customer_id:bigint", "name:varchar", "amount:double", "tax_group_id:bigint", "tax_id:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "order_items": ["id:bigint", "customer_id:bigint", "company_id:bigint", "order_id:bigint", "package_id:bigint", "package_type:enum", "sac_no:varchar", "item_details:longtext", "name:varchar", "quantity:bigint", "unit_price:double", "tax_group_id:bigint", "tax:double", "discount_type:enum", "discount:double", "total:double", "created_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "order_totals": ["id:bigint", "order_id:bigint", "customer_id:bigint", "company_id:bigint", "code:varchar", "name:varchar", "sort_order:int", "amount:double", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "order_transactions": ["id:bigint", "payment_id:int", "order_id:bigint", "customer_id:int", "company_id:int", "status:varchar", "transaction_id:text", "payment_request_id:text", "amount:double", "comment:text", "input_data:text", "response_data:text", "device_name:varchar", "device_id:varchar", "created_at:timestamp", "updated_at:timestamp", "deleted_at:timestamp"],
    "orders": ["id:bigint", "subscription_id:bigint", "company_id:bigint", "parent_user_id:bigint", "invoice_no:bigint", "invoice_prefix:varchar", "invoice_date:datetime", "transaction_id:varchar", "customer_id:bigint", "category_id:int", "first_name:varchar", "last_name:varchar", "email:varchar", "billing_first_name:varchar", "billing_last_name:varchar", "billing_company_name:varchar", "billing_address:text", "payment_method:bigint", "comments:text", "account_id:bigint", "order_total:double", "sub_total:double", "total_tax:double", "balance:double", "coupon_code:bigint", "coupon_details:longtext", "language_code:varchar", "currency_code:varchar", "currency_value:double", "ip:varchar", "user_agent:tinytext", "discount_amount:double", "due_date:timestamp", "payment_status:enum", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "packages": ["id:bigint", "hsn_no:bigint", "name:varchar", "image:varchar", "category_id:bigint", "subscription_limit:int", "description:text", "features:text", "price:double", "mrp:double", "purchase_price:double", "tax_group_id:bigint", "company_id:bigint", "bill_type:enum", "setup_cost:enum", "created_date:date", "duration:int", "connection_type:enum", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "password_reset_tokens": ["email:varchar", "token:varchar", "created_at:timestamp"],
    "payment_histories": ["id:bigint", "company_id:bigint", "parent_user_id:bigint", "customer_id:bigint", "payment_id:bigint", "order_id:bigint", "amount:double", "collected_amount:double", "reference:text", "payment_details:longtext", "created_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "payment_methods": ["id:bigint", "name:varchar", "type:enum", "code:varchar", "order:bigint", "account_id:bigint", "company_id:bigint", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "payments": ["id:bigint", "customer_id:bigint", "account_id:bigint", "category_id:bigint", "company_id:bigint", "parent_user_id:bigint", "payment_type:enum", "payment_method:bigint", "amount:double", "payment_request_id:varchar", "transaction_id:varchar", "customer_detail:text", "wallet_amount:decimal", "image:varchar", "comments:text", "reference:varchar", "description:text", "payment_status:enum", "wallet_money:tinyint", "payment_gateway_status:varchar", "reconciled:tinyint", "currency_code:varchar", "currency_rate:double", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp", "txn_date:timestamp"],
    "permissions": ["id:bigint", "name:varchar", "display_name:varchar", "module:varchar", "guard_name:varchar", "created_at:timestamp", "updated_at:timestamp"],
    "personal_access_tokens": ["id:bigint", "tokenable_type:varchar", "tokenable_id:bigint", "name:varchar", "token:varchar", "abilities:text", "last_used_at:timestamp", "expires_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "problem_types": ["id:bigint", "type:varchar", "description:text", "status:enum", "company_id:int", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "providers": ["id:bigint", "name:varchar", "company_id:bigint", "description:text", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "role_has_permissions": ["permission_id:bigint", "role_id:bigint"],
    "roles": ["id:bigint", "name:varchar", "guard_name:varchar", "company_id:bigint", "created_at:timestamp", "updated_at:timestamp"],
    "settings": ["id:bigint", "company_id:bigint", "parent_user_id:bigint", "financial_year:datetime", "time_zone:varchar", "date_format:varchar", "separator:varchar", "position:varchar", "price_name:varchar", "item_name:varchar", "invoice_prefix:varchar", "invoice_suffix:bigint", "quantity_name:varchar", "due_date:bigint", "icon:varchar", "account:varchar", "currency:varchar", "currency_symbol:varchar", "tax_rate:varchar", "decimal:bigint", "language:varchar", "created_at:timestamp", "updated_at:timestamp"],
    "sms_logs": ["id:bigint", "area_id:bigint", "name:varchar", "customer_id:bigint", "subscriber_id:varchar", "type:varchar", "stb_id:bigint", "stb_no:varchar", "mobile:varchar", "user_id:bigint", "parent_user_id:bigint", "content:tinytext", "template_id:varchar", "sent_status:enum", "response:varchar", "status_date:timestamp", "created_date:timestamp", "company_id:bigint", "enable:tinyint", "data:text", "created_at:timestamp", "updated_at:timestamp"],
    "stbs": ["id:bigint", "stb_no:varchar", "serial_no:varchar", "customer_id:bigint", "company_id:bigint", "parent_user_id:bigint", "provider_id:bigint", "type:varchar", "connection_type:enum", "stb_status:enum", "latitude:double", "longitude:double", "location_address:text", "activated_at:timestamp", "status_date:timestamp", "device_make:varchar", "reference:text", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "tax_groups": ["id:bigint", "title:varchar", "company_id:bigint", "description:text", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "taxes": ["id:bigint", "company_id:bigint", "tax_group_id:bigint", "name:varchar", "code:varchar", "sort_order:bigint", "tax_percentage:double", "description:text", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "temp_customer_imports": ["id:bigint", "subscriber_id:varchar", "lco_no:varchar", "serial:varchar", "first_name:varchar", "last_name:varchar", "address:text", "billing_name:varchar", "billing_address:text", "email:varchar", "mobile:varchar", "status:varchar", "area_id:varchar", "join_date:timestamp", "stb_number:varchar", "serial_no:varchar", "stb_status:varchar", "stb_type:varchar", "stb_make:varchar", "connection_type:varchar", "cas_provider:varchar", "error:varchar", "comments:varchar", "company_id:bigint", "uploaded_by:bigint", "created_at:timestamp", "updated_at:timestamp"],
    "temp_enquiries": ["id:bigint", "name:varchar", "phone:varchar", "email:varchar", "address:text", "source:enum", "product_sku:varchar", "status:enum", "city:varchar", "area:int", "state:varchar", "country:varchar", "company:varchar", "company_id:bigint", "error:varchar", "comments:text", "notes:text", "created_at:timestamp", "updated_at:timestamp"],
    "test_students": ["id:int", "name:varchar", "city:varchar"],
    "topic_subscriptions": ["id:bigint", "user_id:int", "company_id:int", "topic:varchar", "created_at:timestamp", "updated_at:timestamp"],
    "user_companies": ["id:bigint", "user_id:bigint", "company_id:bigint", "area_id:longtext", "created_at:timestamp", "updated_at:timestamp"],
    "users": ["id:bigint", "bq_user_id:int", "parent_user_id:bigint", "first_name:varchar", "last_name:varchar", "email:varchar", "role_id:bigint", "country_code:varchar", "mobile:bigint", "company_id:bigint", "last_login_at:timestamp", "password:varchar", "city:varchar", "state:varchar", "country:varchar", "zip_code:bigint", "latitude:varchar", "longitude:varchar", "status:enum", "locale:varchar", "active_company:bigint", "area_ids:longtext", "email_verified_at:timestamp", "remember_token:varchar", "created_at:timestamp", "updated_at:timestamp", "deleted_at:timestamp"],
    "vendors": ["id:bigint", "company_id:bigint", "title:varchar", "taxIn:varchar", "country_code:varchar", "mobile:varchar", "email:varchar", "address:text", "status:enum", "created_by:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "wallet_logs": ["id:bigint", "user_id:int", "company_id:int", "subscriber_id:varchar", "amount:double", "comments:text", "created_at:timestamp", "updated_at:timestamp"],
    "wallets": ["id:bigint", "company_id:bigint", "parent_user_id:bigint", "account_id:bigint", "payment_id:bigint", "account_code:varchar", "paid_at:datetime", "amount:double", "currency_code:varchar", "currency_rate:varchar", "customer_id:bigint", "description:text", "payment_method:bigint", "reference:varchar", "parent_id:bigint", "user_id:bigint", "deleted_by:bigint", "deleted_at:timestamp", "created_at:timestamp", "updated_at:timestamp"],
    "whatsapp_logs": ["id:bigint", "area_id:bigint", "name:varchar", "customer_id:bigint", "subscriber_id:varchar", "type:varchar", "stb_id:bigint", "stb_no:varchar", "mobile:varchar", "user_id:bigint", "parent_user_id:bigint", "content:tinytext", "sent_status:enum", "response:varchar", "status_date:timestamp", "created_date:timestamp", "company_id:bigint", "enable:tinyint", "data:text", "created_at:timestamp", "updated_at:timestamp"],
}

TABLES_WITH_COMPANY_ID = {
    "accounts",
    "add_ons",
    "areas",
    "bq_ai_query_logs",
    "bq_app_users",
    "categories",
    "complaint_forums",
    "complaints",
    "customer_add_on_histories",
    "customer_add_ons",
    "customer_dues_logs",
    "customer_subscription_histories",
    "customer_subscriptions",
    "customers",
    "default_payment_methods",
    "demand_pay_access_logs",
    "demand_pay_tokens",
    "device_tokens",
    "enquiries",
    "expenses",
    "followups",
    "headers",
    "incomes",
    "items",
    "leads",
    "master_plans",
    "message_channel_settings",
    "message_notification_settings",
    "notifications",
    "order_histories",
    "order_item_taxes",
    "order_items",
    "order_totals",
    "order_transactions",
    "orders",
    "packages",
    "payment_histories",
    "payment_methods",
    "payments",
    "problem_types",
    "providers",
    "roles",
    "settings",
    "sms_logs",
    "stbs",
    "tax_groups",
    "taxes",
    "temp_customer_imports",
    "temp_enquiries",
    "topic_subscriptions",
    "user_companies",
    "users",
    "vendors",
    "wallet_logs",
    "wallets",
    "whatsapp_logs",
}
